#!/bin/bash

# Written with Claude Code

# Regenerates src/programs/.clangd from the actual i686-brebos-g++ toolchain
# on disk, instead of hand-typing its header search paths.
#
# clangd can't be told to query the cross compiler itself (CLion's bundled
# clangd has no --query-driver option), so we ask gcc for its own search
# list and bake it in. Re-run this after rebuilding/moving the toolchain.
set -e

BREBOS=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TOOLCHAIN_DIR="$BREBOS/toolchain"
CXX="$TOOLCHAIN_DIR/usr/bin/i686-brebos-g++"

if [ ! -x "$CXX" ]; then
  echo "error: $CXX not found (build the toolchain first)" >&2
  exit 1
fi

export PATH="$TOOLCHAIN_DIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$TOOLCHAIN_DIR/usr/lib:$TOOLCHAIN_DIR/usr/x86_64-pc-linux-gnu/i686-brebos/lib:$LD_LIBRARY_PATH"

ISYSTEM_PATHS=$(echo | "$CXX" -std=c++20 -v -E -x c++ - 2>&1 \
  | sed -n '/#include <\.\.\.> search starts here/,/End of search list/p' \
  | sed '1d;$d' \
  | sed 's/^ *//' \
  | xargs -I{} realpath -m {})

OUT="$BREBOS/src/programs/.clangd"

{
  echo "# Auto-generated by utils/gen_clangd.sh - do not edit by hand."
  echo "# Regenerate after rebuilding/moving the toolchain: ./utils/gen_clangd.sh"
  echo "#"
  echo "# Programs are cross-compiled with the project's own i686-brebos-g++ (see"
  echo "# program_Makefile), targeting i686-brebos with its own GCC libstdc++, not"
  echo "# the host compiler/standard library. Without this, clangd falls back to a"
  echo "# guessed compiler/standard/libstdc++ version, causing false positives in"
  echo "# headers like <format> that don't show up in the real build."
  echo "CompileFlags:"
  echo "  Add:"
  echo "    # Force a 64-bit target for clangd's own parsing, overriding any"
  echo "    # i686-brebos triple it may auto-infer from the compiler name. Clang"
  echo "    # (unlike GCC) doesn't support __float128 on 32-bit x86 at all, which"
  echo "    # some GCC-target headers reference; this only affects clangd's"
  echo "    # syntax-only parse, not the real i686 build."
  echo "    - --target=x86_64-unknown-linux-gnu"
  echo "    - -std=c++20"
  echo "    - -nostdinc++"
  echo "    - -nostdinc"
  while IFS= read -r p; do
    [ -n "$p" ] && echo "    - -isystem$p"
  done <<< "$ISYSTEM_PATHS"
  echo "    - -I$BREBOS/src/libk"
  echo "    - -Wall"
  echo "    - -Wextra"
} > "$OUT"

echo "wrote $OUT"
